// front-end/src/lib/components/Header.svelte
<script lang="ts">
  import { resolve } from "$app/paths";
  import headerImage from "$lib/assets/header.jpg";
  import ThemeToggle from "$lib/components/ThemeToggle.svelte";
</script>

<header
  class="relative border-b border-gray-800 text-white"
  style={`background-image: linear-gradient(to right, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.4)), url(${headerImage}); background-position: center; background-size: cover;`}
>
  <div class="container mx-auto px-6">
    <div class="flex items-center justify-between">
      <nav class="py-6" aria-label="Main navigation">
        <ul class="flex items-center space-x-8">
          <li class="hidden lg:block">
            <a
              class="font-poppins-heading text-white transition-colors hover:text-primary-200"
              href={resolve("/")}
              aria-label="Home"
            >
              <h1 class="text-2xl italic">WeLoveMovies</h1>
            </a>
          </li>
          <li>
            <a
              class="text-lg text-white transition-colors hover:text-primary-200"
              href={resolve("/movies")}
              aria-label="View all movies"
            >
              All Movies
            </a>
          </li>
          <li>
            <a
              class="text-lg text-white transition-colors hover:text-primary-200"
              href={resolve("/theaters")}
              aria-label="View all theaters"
            >
              All Theaters
            </a>
          </li>
        </ul>
      </nav>
      <ThemeToggle />
    </div>
    <div class="py-12">
      <h1
        class="mb-4 text-5xl font-poppins-heading tracking-tight drop-shadow-[0_2px_4px_rgba(0,0,0,0.4)]"
      >
        Find your next favorite movie!
      </h1>
      <p class="text-2xl font-light drop-shadow-[0_1px_2px_rgba(0,0,0,0.3)]">
        <em class="font-medium">WeLoveMovies</em> is your source for finding reviews
        of movies in theaters near you.
      </p>
    </div>
  </div>
</header>

// front-end/src/shared/Header.tsx
import React from "react";
import HeaderNav from "./HeaderNav";
import ThemeToggle from "./theme/ThemeToggle";
import headerImage from "./header.jpg";

interface HeaderStyles extends React.CSSProperties {
  background: string;
  backgroundPosition: string;
  backgroundSize: string;
}

/**
 * Header Component
 * Displays the main header section with navigation, theme toggle, and welcome message
 * @returns JSX element displaying the header with background image and content
 */
const Header: React.FC = () => {
  return (
    <header
      className="relative text-white border-b border-gray-800"
      style={{
        backgroundImage: `linear-gradient(to right, rgba(0, 0, 0, 0.8), rgba(0, 0, 0, 0.4)), url(${headerImage})`,
        backgroundPosition: "center",
        backgroundSize: "cover"
      }}
    >
      <div className="container mx-auto px-6">
        <div className="flex justify-between items-center">
          <HeaderNav />
          <ThemeToggle />
        </div>
        <div className="py-12">
          <h1 className="text-5xl font-poppins-heading mb-4 drop-shadow-[0_2px_4px_rgba(0,0,0,0.4)] tracking-tight">
            Find your next favorite movie!
          </h1>
          <p className="text-2xl font-light drop-shadow-[0_1px_2px_rgba(0,0,0,0.3)]">
            <em className="font-medium">WeLoveMovies</em> is your source for finding reviews of movies in
            theaters near you.
          </p>
        </div>
      </div>
    </header>
  );
};

export default Header;
