// front-end/src/lib/components/ProgressiveImage.svelte
<script lang="ts">
  import { theme } from "$lib/stores/theme";

  let { src, alt, class: className = "" }: { src: string; alt: string; class?: string } = $props();
  let isLoaded = $state(false);
  let hasError = $state(false);
</script>

<div class={`relative overflow-hidden ${className} ${$theme === "dark" ? "bg-gray-700" : "bg-gray-200"} ${!isLoaded ? "animate-pulse" : ""}`}>
  {#if hasError}
    <div class="absolute inset-0 flex items-center justify-center bg-gray-200 dark:bg-gray-800">
      <span class="text-gray-500 dark:text-gray-400">Failed to load image</span>
    </div>
  {:else}
    <img
      {src}
      {alt}
      class={`h-full w-full object-cover transition-opacity duration-300 ${isLoaded ? "opacity-100" : "opacity-0"}`}
      loading="lazy"
      onload={() => (isLoaded = true)}
      onerror={() => (hasError = true)}
    />
  {/if}
</div>

// front-end/src/shared/components/ProgressiveImage.tsx
import React, { useState, useEffect } from "react";
import { useInView } from "react-intersection-observer";
import { useTheme } from "../theme/ThemeContext";

interface ProgressiveImageProps {
  src: string;
  alt: string;
  className?: string;
}

export const ProgressiveImage: React.FC<ProgressiveImageProps> = ({
  src,
  alt,
  className = "",
}) => {
  const [isLoaded, setIsLoaded] = useState(false);
  const [error, setError] = useState(false);
  const { theme } = useTheme();
  const { ref, inView } = useInView({
    triggerOnce: true,
    rootMargin: "50px 0px",
  });

  useEffect(() => {
    if (inView && !isLoaded && !error) {
      const img = new Image();
      img.src = src;
      img.onload = () => setIsLoaded(true);
      img.onerror = () => setError(true);
    }
  }, [inView, src, isLoaded, error]);

  return (
    <div
      ref={ref}
      className={`relative overflow-hidden ${className} ${
        theme === "dark" ? "bg-gray-700" : "bg-gray-200"
      } ${!isLoaded && "animate-pulse"}`}
    >
      {error ? (
        <div className="absolute inset-0 flex items-center justify-center bg-gray-200 dark:bg-gray-800">
          <span className="text-gray-500 dark:text-gray-400">
            Failed to load image
          </span>
        </div>
      ) : (
        <img
          src={src}
          alt={alt}
          className={`w-full h-full object-cover transition-opacity duration-300 ${
            isLoaded ? "opacity-100" : "opacity-0"
          }`}
          loading="lazy"
        />
      )}
    </div>
  );
};
